/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnstringifyIndexRouteImport } from './routes/unstringify/index'
import { Route as StringifyIndexRouteImport } from './routes/stringify/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnstringifyIndexRoute = UnstringifyIndexRouteImport.update({
  id: '/unstringify/',
  path: '/unstringify/',
  getParentRoute: () => rootRouteImport,
} as any)
const StringifyIndexRoute = StringifyIndexRouteImport.update({
  id: '/stringify/',
  path: '/stringify/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stringify': typeof StringifyIndexRoute
  '/unstringify': typeof UnstringifyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stringify': typeof StringifyIndexRoute
  '/unstringify': typeof UnstringifyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stringify/': typeof StringifyIndexRoute
  '/unstringify/': typeof UnstringifyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/stringify' | '/unstringify'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/stringify' | '/unstringify'
  id: '__root__' | '/' | '/stringify/' | '/unstringify/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StringifyIndexRoute: typeof StringifyIndexRoute
  UnstringifyIndexRoute: typeof UnstringifyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unstringify/': {
      id: '/unstringify/'
      path: '/unstringify'
      fullPath: '/unstringify'
      preLoaderRoute: typeof UnstringifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stringify/': {
      id: '/stringify/'
      path: '/stringify'
      fullPath: '/stringify'
      preLoaderRoute: typeof StringifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StringifyIndexRoute: StringifyIndexRoute,
  UnstringifyIndexRoute: UnstringifyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
